### ISSUE TITLE
[Bug|Unexpected] Shows 2 windows with '--show' flag and client's `useIframe` 

### ISSUE THREAD

**Issue by luchillo17** [twolfson/karma-electron#21]
## Background
I have an Electron app with Webpack, Typescript and Karma support (karma part WIP).

## Problem
Originally when run it only shows the karma electron browser in launch bar, and the test output in the terminal, so far so good.

But when i use the `client`'s `useIframe: false` property and the `--show` flag in the `customLaunchers.CustomElectron` it shows 2 windows, 1 for the karma testing GUI (which is almost the same as terminal) and another white screen window.

Interesting note: The second window is always white, but when i press the `Debug` button in the main karma window, a third one shows with my app in there as well as the specs logs, it would be cool if that window was the actual one shown by the flags in question.

## Guesses
* I guess either is a bug showing 2 windows, or the actual app is intended to show in that second window and it's bugged.
* Also i think the `__filenameOverride` property mentioned in (script-configuration)[https://github.com/twolfson/karma-electron#script-configuration] is meant to go side to side with the `--show` flag.
* Based on previous 2 guesses, my issue is that since Webpack generates it's own html, and it stays only in memory, i can't access it at config time since it hasn't been created, nor can i use an url, because the `karma-webpack` lib doesn't compile with `webpack-dev-server`.

## Steps to reproduce
* Clone my repo about [Electron-Webpack](https://github.com/Luchillo/Electron-Webpack).
* Switch to `feature/Testing` branch.
* Run `npm i && npm run watch:test` in terminal in the cloned repo folder.
* At this point 2 windows pop out, 1 is karma's  result, the 2º is white.
* Click the `Debug` button in Karma's window to see the actual app.

**Comment by twolfson** [comment]
This is expected behavior. When we shut off `useIframe`, Karma moves to using `window.open` instead so there are 2 windows:

- Karma's test harness (communicates to Node.js, starts new test runs)
- Karma's test runner (loads testing framework/test files, communicates success/fail information to test harness via `window.parent`)

To demonstrate this point further, we could disable `useIframe` in other browsers and see the same result (e.g. Chrome, Firefox)

**Comment by luchillo17** [comment]
The thing is that without `useIframe: false` we lose `nodeIntegration`, but with it, it shows 2 windows, with the second being incredibly annoying poping up all the time.

I guess the idea is to run with `--show` flag off and only show when we need to debug the tests, right?

**Comment by twolfson** [comment]
Yep, typically showing the window isn't too helpful as content is often added/remove quicker than we can see. To make it less painful to add/remove the `--show` flag in `karma.conf.js`, I use the following setup:

**Add `ElectronVisible` browser but don't set it as default browser:**

```js
    browsers: ['Electron'],
    customLaunchers: {
      ElectronVisible: {
        base: 'Electron',
        flags: ['--show']
      }
    }
```

**Override default browsers via CLI:**

```bash
karma start --browsers ElectronVisible
# or for `npm-scripts`
npm run test-karma -- --browsers ElectronVisible
```

**Comment by luchillo17** [comment]
Nice 😄
