### ISSUE TITLE
[feature] option like 'require', but for renderer processes.

### ISSUE THREAD

**Issue by trusktr** [twolfson/karma-electron#45]
The `require` option for karma-electron operates in the main process. But having one that `require`s stuff in the renderer processes might be useful (f.e. maybe I could find a way to hack the node require paths that way, which might help with https://github.com/twolfson/karma-electron/issues/44).

**Comment by twolfson** [comment]
I believe my response in https://github.com/twolfson/karma-electron/issues/44#issuecomment-596133385 has answered this. If not, please let me know
