### ISSUE TITLE
There is no test result feed back

### ISSUE THREAD

**Issue by fallenleavesguy** [twolfson/karma-electron#8]
I have followed this [https://github.com/twolfson/karma-electron/blob/3.2.1/docs/submodules.md](https://github.com/twolfson/karma-electron/blob/3.2.1/docs/submodules.md) to config my karma.

There is no error, but I didn't get any feed back from my test or any js files.Then I modified a file and save it. It seem electron was pending. and log this:

``` shell
20 06 2016 18:14:31.646:INFO [karma]: Delaying execution, these browsers are not ready: Electron 1.2.3 (Node 6.1.0)
```

**Comment by fallenleavesguy** [comment]
I make electron window visibled, but I don't see anything in the chrome inspector, like this:
<img width="799" alt="screen shot 2016-06-20 at 6 23 15 pm" src="https://cloud.githubusercontent.com/assets/9261562/16190885/1a88fe1c-3714-11e6-9a51-a9f1ec1e0678.png">

**Comment by fallenleavesguy** [comment]
I don't know why, but I fixed this by refollow the readme, I can't reproduce this issue now.

**Comment by twolfson** [comment]
I'm glad to hear the issue has been resolved =)
